CREATE TABLE APP_ACTIVITY_LOG (
	LOG_SEQ				NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1)	NOT NULL,
	ONLINE_SITE_CODE	VARCHAR2(32)		NOT NULL,
	SESSION_ID			VARCHAR2(128)		NULL,
	CUSTOMER_SEQ		VARCHAR2(128)	NULL,
	ACCESS_TYPE			VARCHAR2(32)		NOT NULL,
	REFERER_FULL_URL	VARCHAR2(2000)		NULL,
	REFERER_URL			VARCHAR2(500)		NULL,
	URL					VARCHAR2(128)		NULL,
	API_URL				VARCHAR2(128)		NULL,
	MAIN_DATA			VARCHAR2(300)		NULL,
	REQUEST_JSON		CLOB				NULL,
	CREATE_DATE			DATE				DEFAULT SYSDATE	NOT NULL,
	CONSTRAINT PK_APP_ACTIVITY_LOG PRIMARY KEY (LOG_SEQ)
) TABLESPACE TBS_KM;
COMMENT ON TABLE APP_ACTIVITY_LOG IS '활동로그';
COMMENT ON COLUMN APP_ACTIVITY_LOG.LOG_SEQ IS '로그일련번호';
COMMENT ON COLUMN APP_ACTIVITY_LOG.ONLINE_SITE_CODE IS '온라인사이트코드';
COMMENT ON COLUMN APP_ACTIVITY_LOG.SESSION_ID IS '세션아이디';
COMMENT ON COLUMN APP_ACTIVITY_LOG.CUSTOMER_SEQ IS '고객일련번호';
COMMENT ON COLUMN APP_ACTIVITY_LOG.ACCESS_TYPE IS '접근유형';
COMMENT ON COLUMN APP_ACTIVITY_LOG.URL IS 'URL';
COMMENT ON COLUMN APP_ACTIVITY_LOG.MAIN_DATA IS '메인 데이터';
COMMENT ON COLUMN APP_ACTIVITY_LOG.REFERER_FULL_URL IS '이전 경로 URL';
COMMENT ON COLUMN APP_ACTIVITY_LOG.REFERER_URL IS 'REFERER URL';
COMMENT ON COLUMN APP_ACTIVITY_LOG.API_URL IS 'API URL';
COMMENT ON COLUMN APP_ACTIVITY_LOG.REQUEST_JSON IS 'REQUEST JSON';
COMMENT ON COLUMN APP_ACTIVITY_LOG.CREATE_DATE IS '등록일';


CREATE TABLE LOG_BPS_RESULT (
	LOG_SEQ						NUMBER				GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1)	NOT NULL,
	SYSTEM_CODE					VARCHAR2(32)		NOT NULL,
	BPS_TYPE_CODE				VARCHAR2(32)		NOT NULL,
	FRONT_URL					VARCHAR2(255)		NULL,
	REQUEST_URL					VARCHAR2(255)		NOT NULL,
	REQUEST_HEADER				VARCHAR2(4000)		NULL,
	REQUEST_PARAM				CLOB				NULL,
	REQUEST_BODY				CLOB				NULL,
	IP							VARCHAR2(255)		NULL,
	USER_ID						VARCHAR2(128)		NOT NULL,
	EMPLOYEE_CODE 				VARCHAR2(128)		NULL,
	CREATE_DATE					DATE				DEFAULT SYSDATE		NOT NULL,
	CONSTRAINT PK_LOG_BPS_RESULT PRIMARY KEY (log_seq)
) TABLESPACE TBS_THEKARY;
COMMENT ON TABLE LOG_BPS_RESULT IS 'BPS LOG';
COMMENT ON COLUMN LOG_BPS_RESULT.log_seq IS '로그 일련번호';
COMMENT ON COLUMN LOG_BPS_RESULT.SYSTEM_CODE IS '시스템코드';
COMMENT ON COLUMN LOG_BPS_RESULT.BPS_TYPE_CODE IS 'BPS유형코드';
COMMENT ON COLUMN LOG_BPS_RESULT.FRONT_URL IS '프론트 URL';
COMMENT ON COLUMN LOG_BPS_RESULT.REQUEST_URL IS '요청 URL';
COMMENT ON COLUMN LOG_BPS_RESULT.REQUEST_HEADER IS '요청 헤더';
COMMENT ON COLUMN LOG_BPS_RESULT.REQUEST_PARAM IS '요청 파라미터';
COMMENT ON COLUMN LOG_BPS_RESULT.REQUEST_BODY IS '요청 바디';
COMMENT ON COLUMN LOG_BPS_RESULT.IP IS 'IP';
COMMENT ON COLUMN LOG_BPS_RESULT.USER_ID IS '사용자ID';
COMMENT ON COLUMN LOG_BPS_RESULT.EMPLOYEE_CODE IS '직원코드';
COMMENT ON COLUMN LOG_BPS_RESULT.CREATE_DATE IS '등록일';
